<a href="https://colab.research.google.com/github/adityav1810/ExploringPytorch/blob/main/Playing_with_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()


Using device: cuda



In [3]:
x = torch.tensor([5.],requires_grad = True)
w = torch.tensor([2.],requires_grad=True)

In [4]:
'''
x = 5
w = 2

y = wx^2
dy/dx = 2 wx => ( 2.2.5 )=> 20
dy / dw = x^2 => (5^2) => 25
'''
def f(w,x):
  return w * (x**2)
y = f(w,x)
y.backward()


In [5]:
'''
Computes dy/dw ie
'''
print("Gradient of Y w.rt. W ",w.grad)

Gradient of Y w.rt. W  tensor([25.])


In [6]:
'''
Computes dy/dx ie
'''
print("Gradient of Y w.rt. X ",x.grad)

Gradient of Y w.rt. X  tensor([20.])


In [7]:
def neuron(w,x,b):
  return torch.add(torch.matmul(w,x),b)
w = torch.tensor([3.,4.,3.],requires_grad = True)
x = torch.tensor([7.,1.,2.],requires_grad = True)
b = torch.tensor([1.,1.,1.],requires_grad = True)
n = neuron(w,x,b)


In [8]:
n.sum().backward()

In [9]:
w.grad,x.grad,b.grad

(tensor([21.,  3.,  6.]), tensor([ 9., 12.,  9.]), tensor([1., 1., 1.]))

In [10]:
n

tensor([32., 32., 32.], grad_fn=<AddBackward0>)

In [11]:


inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])


In [15]:
def exp_adder(x, y):
    return 2 * x.exp() + 3 * y
inputs = (w,x)
torch.autograd.functional.jacobian(exp_adder, inputs)

(tensor([[ 40.1711,   0.0000,   0.0000],
         [  0.0000, 109.1963,   0.0000],
         [  0.0000,   0.0000,  40.1711]]),
 tensor([[3., 0., 0.],
         [0., 3., 0.],
         [0., 0., 3.]]))